# Generated by Django 5.2.7 on 2025-10-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_transcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='error',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='transcript_text',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='video_url',
        ),
        migrations.AddField(
            model_name='transcription',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transcription',
            name='temp_video_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='video_id',
            field=models.CharField(max_length=255),
        ),
    ]
