# Generated by Django 5.2.7 on 2025-10-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_remove_transcription_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='duration',
        ),
    ]
