# Generated by Django 5.2.7 on 2025-12-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0004_remove_transcription_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
