# """
# Django settings for tiknote project.

# Generated by 'django-admin startproject' using Django 5.2.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# import os
# from pathlib import Path
# from dotenv import load_dotenv



# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(BASE_DIR / ".env")

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# # ALLOWED_HOSTS = []

# CSRF_TRUSTED_ORIGINS = [
#     "https://alexis-untrailered-soakingly.ngrok-free.dev",
# ]

# ALLOWED_HOSTS = [
#     "127.0.0.1",
#     "localhost",
#     "alexis-untrailered-soakingly.ngrok-free.dev",
# ]




# if DEBUG:
#     CSRF_TRUSTED_ORIGINS = [
#         "https://alexis-untrailered-soakingly.ngrok-free.dev",
#         "http://127.0.0.1:8000",
#         "http://localhost:8000",
#     ]
#     CSRF_COOKIE_SECURE = False
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_DOMAIN = None
#     SESSION_COOKIE_DOMAIN = None
# else:
#     # Production
#     CSRF_COOKIE_SECURE = True
#     SESSION_COOKIE_SECURE = True



# # Session configuration
# SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Store sessions in the database
# SESSION_COOKIE_NAME = "sessionid"
# SESSION_COOKIE_AGE = 1209600  # 2 weeks
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# # SESSION_COOKIE_SAMESITE = "None"
# # SESSION_COOKIE_SECURE = False


# SESSION_COOKIE_HTTPONLY = True
# # SESSION_COOKIE_SAMESITE = 'Lax'  # Important for OAuth redirects
# # SESSION_COOKIE_SECURE = False  # Set to True only in production with HTTPS
# SESSION_SAVE_EVERY_REQUEST = True  # Force session save on every request
# # SESSION_COOKIE_AGE = 1200  # 20 minutes (enough for OAuth flow)




# SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# DEBUG = os.getenv("DEBUG", "False") == "True"

# # For development, ensure cookies work on localhost
# if DEBUG:
#     SESSION_COOKIE_SECURE = False
#     SESSION_COOKIE_SAMESITE = 'Lax'


# TIKTOK_CLIENT_KEY = os.getenv("TIKTOK_CLIENT_KEY")
# TIKTOK_CLIENT_SECRET = os.getenv("TIKTOK_CLIENT_SECRET")
# TIKTOK_REDIRECT_URI = os.getenv("TIKTOK_REDIRECT_URI")
# CSRF_COOKIE_SECURE = True



# # Rate limiting
# RATELIMIT_ENABLE = True
# RATELIMIT_USE_CACHE = 'default'

# # Silence django-ratelimit cache warnings in development
# SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': 'app.log',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#     },
# }



# # CACHES = {
# #     'default': {
# #         'BACKEND': 'django_redis.cache.RedisCache',
# #         'LOCATION': 'redis://127.0.0.1:6379/1',
# #         'OPTIONS': {
# #             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
# #         }
# #     }
# # }


# # In your settings.py, replace the CACHES section with:

# # if DEBUG:
# #     # Use local memory cache for development (no Redis needed)
# #     CACHES = {
# #         'default': {
# #             'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
# #             'LOCATION': 'unique-snowflake',
# #         }
# #     }
# # else:
# #     # Use Redis for production
# #     CACHES = {
# #         'default': {
# #             'BACKEND': 'django_redis.cache.RedisCache',
# #             'LOCATION': 'redis://127.0.0.1:6379/1',
# #             'OPTIONS': {
# #                 'CLIENT_CLASS': 'django_redis.client.DefaultClient',
# #             }
# #         }
# #     }
    

# if DEBUG:
#     # Use database cache for development (no Redis needed)
#     CACHES = {
#         'default': {
#             'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#             'LOCATION': 'cache_table',
#         }
#     }
# else:
#     # Use Redis for production
    
#     CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }
#     # CACHES = {
#     #     'default': {
#     #         'BACKEND': 'django_redis.cache.RedisCache',
#     #         'LOCATION': 'redis://127.0.0.1:6379/1',
#     #         'OPTIONS': {
#     #             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#     #         }
#     #     }
#     # }



# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
    
#     'rest_framework',
    
#     'django_celery_beat',
#     'django_celery_results',
#     'django_ratelimit',
    
#     'accounts',
#     'profiles',
#     'transcripts',
#     'feeds',
#     'interactions',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     # 'tiknote.middleware.rate_limit.RateLimitMiddleware',
# ]

# ROOT_URLCONF = 'tiknote.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'tiknote.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# LOGIN_URL = '/accounts/tiktok/login/'
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'


# MEDIA_ROOT = BASE_DIR / "media"
# MEDIA_URL = "/media/"

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# # # Celery setup for Development (No Redis needed)
# # CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# # # Use memory broker for development (no Redis needed)
# # CELERY_BROKER_URL = 'memory://'

# # # Use Django database to store results
# # CELERY_RESULT_BACKEND = 'django-db'
# # CELERY_CACHE_BACKEND = 'django-cache'

# # CELERY_BROKER_URL = 'redis://localhost:6379/0'
# # CELERY_RESULT_BACKEND = 'django-db'
# # # CELERY_TASK_ALWAYS_EAGER = False

# # # Run tasks synchronously in development (no separate worker needed)
# # CELERY_TASK_ALWAYS_EAGER = True  # ✅ Changed to True
# # CELERY_TASK_EAGER_PROPAGATES = True  # ✅ Added this

# # CELERY_ACCEPT_CONTENT = ["json"]
# # CELERY_TASK_SERIALIZER = "json"
# # CELERY_RESULT_SERIALIZER = "json"
# # CELERY_TIMEZONE = "Africa/Lagos"



# # Celery Configuration
# # ===================

# # For Development: Use synchronous execution (no Redis/worker needed)
# if DEBUG:
#     # Run tasks immediately in the same process
#     CELERY_TASK_ALWAYS_EAGER = False
#     CELERY_TASK_EAGER_PROPAGATES = False
#     CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
#     CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
#     CELERY_CACHE_BACKEND = 'django-cache'
    
# else:
#     # For Production: Use Redis
#     CELERY_BROKER_URL = 'redis://localhost:6379/0'
#     CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
#     CELERY_CACHE_BACKEND = 'default'
#     CELERY_TASK_ALWAYS_EAGER = False
#     CELERY_TASK_EAGER_PROPAGATES = False

# # Common Celery settings
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Africa/Lagos'

# # Task execution settings
# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
# CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit at 25 minutes

# # Retry settings
# CELERY_TASK_ACKS_LATE = True  # Tasks are acknowledged after completion
# CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # One task at a time per worker

# # Result backend settings
# CELERY_RESULT_EXTENDED = True
# CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
# CELERY_RESULT_BACKEND_MAX_RETRIES = 10





# 









"""
Django settings for tiknote project.
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# =============================================================================
# PATHS & ENVIRONMENT
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# =============================================================================
# CORE
# =============================================================================

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'django_celery_beat',
    'django_celery_results',
    'django_ratelimit',

    'accounts',
    'profiles',
    'transcripts',
    'feeds',
    'interactions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tiknote.urls'
WSGI_APPLICATION = 'tiknote.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# =============================================================================
# DATABASE
# =============================================================================

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# AUTHENTICATION & REDIRECTS
# =============================================================================

LOGIN_URL = '/accounts/tiktok/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =============================================================================
# TIKTOK
# =============================================================================

TIKTOK_CLIENT_KEY = os.getenv("TIKTOK_CLIENT_KEY")
TIKTOK_CLIENT_SECRET = os.getenv("TIKTOK_CLIENT_SECRET")
TIKTOK_REDIRECT_URI = os.getenv("TIKTOK_REDIRECT_URI")

# =============================================================================
# SECURITY & COOKIES
# =============================================================================

if DEBUG:
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None
    CSRF_TRUSTED_ORIGINS = [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "https://alexis-untrailered-soakingly.ngrok-free.dev",
    ]
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_DOMAIN = None
else:
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# =============================================================================
# CACHE & REDIS
# =============================================================================

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1")

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# =============================================================================
# CELERY
# =============================================================================

CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")

CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = False

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Lagos'

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_POOL = 'solo'

CELERY_RESULT_EXTENDED = True
CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
CELERY_RESULT_BACKEND_MAX_RETRIES = 10

# =============================================================================
# RATE LIMITING
# =============================================================================

RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =============================================================================
# STATIC & MEDIA
# =============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'transcripts': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}