# Generated by Django 5.2.7 on 2025-10-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_oauthstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
