# Generated by Django 5.2.7 on 2026-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='union_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
